// <auto-generated />
using System;
using FinalTaskFinanceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalTaskFinanceAPI.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260430212127_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("FinalTaskFinanceAPI.Models.ExpenseCategory", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("FinalTaskFinanceAPI.Models.ExpenseItem", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseCategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("ExpenseCategoryName");

                    b.ToTable("ExpenseItems");
                });

            modelBuilder.Entity("FinalTaskFinanceAPI.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseItemName");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinalTaskFinanceAPI.Models.ExpenseItem", b =>
                {
                    b.HasOne("FinalTaskFinanceAPI.Models.ExpenseCategory", null)
                        .WithMany("Items")
                        .HasForeignKey("ExpenseCategoryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalTaskFinanceAPI.Models.Transaction", b =>
                {
                    b.HasOne("FinalTaskFinanceAPI.Models.ExpenseItem", null)
                        .WithMany("Transactions")
                        .HasForeignKey("ExpenseItemName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalTaskFinanceAPI.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FinalTaskFinanceAPI.Models.ExpenseItem", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
